### ISSUE TITLE
Error when filename contains certain characters

### ISSUE THREAD

**Issue by bendwyer** [thebigmunch/gmusicapi-wrapper#12]
When using `gmdownload "/mnt/%albumartist%/%album%/%track2%. %title%"`, I encounter the following error partway through:

```
(###/###) Successfully downloaded -- /mnt/Calvin Harris/I Created Disco/15. We're All The Same.mp3 (334781ca-b5b9-33a1-94df-053fef2a62b7)
(###/###) Successfully downloaded -- /mnt/Calvin Harris/Sweet Nothing/01. Sweet Nothing (Diplo + Grandtheft Remix).mp3 (d001ce3e-fe99-3968-916a-efc03585e254)
Traceback (most recent call last):
  File "/root/gmusic/bin/gmdownload", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.5.0', 'console_scripts', 'gmdownload')()
  File "/root/gmusic/lib/python3.5/site-packages/gmusicapi_scripts/gmdownload.py", line 107, in main
    mmw.download(songs_to_download, template=cli['output'])
  File "/root/gmusic/lib/python3.5/site-packages/gmusicapi_wrapper/decorators.py", line 22, in wrapper
    return function(*args, **kwargs)
  File "/root/gmusic/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 215, in download
    for result in self._download(songs, template):
  File "/root/gmusic/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 181, in _download
    shutil.move(temp.name, filepath)
  File "/root/gmusic/lib/python3.5/shutil.py", line 527, in move
    if os.path.isdir(dst):
  File "/root/gmusic/lib/python3.5/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 54: ordinal not in range(128)
```
I'm not sure exactly what it's saying, but the last line leads me to believe that it can't take the `ë` and put it into the filename.

The next song that would be downloaded would be formatted as such:
```
/mnt/Calvin Harris/Sweet Nothing/02. Sweet Nothing (Tiësto Remix).mp3
```

Using `%suggested%` also stops in the same place with the same error.

What can I do to get around this?

**Comment by thebigmunch** [comment]
Check your ``locale`` to see if it's UTF-8.

**Comment by bendwyer** [comment]
That did the trick. Thanks!
